language: cpp

dist: bionic
sudo: required

matrix:
  include:
    # GCC with tests
    - os: linux
      compiler: gcc
      env: TEST="-DBUILD_TESTS=ON"
    # Clang without tests
    - os: linux
      compiler: clang
      env: TEST="-DBUILD_TESTS=OFF"
    - os: osx
      compiler: clang
      env: TEST="-DBUILD_TESTS=OFF"


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt update -qq;
      sudo apt install -y libasio-dev libgtest-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install asio;
    fi
  - mkdir build
  - cd build

script:
  - cmake -DBUILD_EXAMPLES=ON $TEST ..
  - make
